# -*- coding: utf-8 -*-
"""python 課題14

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hMr_uhjp09I_hHs675k8gQkPMn75T_Lt
"""

price1 = 100
price2 = 200

def total():
    tax = 1.1
    return (price1 + price2) * tax

total()