# -*- coding: utf-8 -*-
"""python 課題17

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OEKBkNKR_gucEgf0CJJJPz0MeyksJUxZ
"""

class Human:
  def __init__(self, name, age):
    self.name = name
    self.age = age

  def check_adult(self, age):
    if age > 20:
      print("大人です。")
    else:
      print("大人ではありません。")

tanaka = Human(name = "田中", age = 21)
asano = Human(name = "浅野", age = 18)

tanaka.check_adult(21)
asano.check_adult(18)