# -*- coding: utf-8 -*-
"""python 課題8

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q_hMMacLQ5TkZk-rRNjnBylVyfALFKxf
"""

import random

var = random.randint(3,15)
print(var)

if var % 15 == 0:
  print("FizzBuzz")
elif var % 3 == 0:
  print("Fizz")
elif var % 5 == 0:
  print("Buzz")

