# -*- coding: utf-8 -*-
"""python 課題11

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FpNDwzE4XRhNfs_ArLJ7hgieCZRxx4SQ
"""

list = ["水","金","地","火","木","土","天","海","冥"]
target = "冥"

for i in list:
  print(i)

i = 0
while i <= 8:
  print(list[i])
  i += 1