# -*- coding: utf-8 -*-
"""python 課題5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZE96uhm2ycDMbwsL1no1LqWpYIDMRcMe
"""

top_side = 10
bottom_side = 20
height = 5
area = (top_side + bottom_side) * height / 2

print(f"台形の面積は{area}cm2です")