# -*- coding: utf-8 -*-
"""python 課題15

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14QXiqiGVO-ro_4CyJOJdZ8us0WHbilCZ
"""

class Human:
  def __init__(self, name, age):
    self.name = name
    self.age = age

  def printinfo(self):
    print(f"私の名前は{self.name}です。")
    print(f"私は{self.age}歳です。")

tanaka = Human(name = "田中", age = 21)
sato = Human(name = "佐藤", age = 28)

tanaka.printinfo()