# -*- coding: utf-8 -*-
"""python_課題13

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tVZdqi-sP4c8ULY4e5Zx6uCyQd9cAXV2
"""

def calculate_consumption_tax(price) -> int:
  return price * 1.1

calculate_consumption_tax(1200)