# -*- coding: utf-8 -*-
"""python 課題13

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H1_2OyQIZa5DmRg_0cIgmEFMwJRWdbn7
"""

print(45+18)

print(1+2)

print(30-12)

print(15*6)



print(45 % 8)
print(type(30/3))
print(45+1.8)
print(3-1.2)
print(15 * 0.6)
print(3 / 0.3)
print(45 % 0.8)
print("今日の天気は"+"晴れ")
print("今日の天気は"+"曇り")
print("降水確率"+str(50)+"%")
print("トラ" * 5)

user_name= "侍太郎"
print(user_name)
user_name= "有村大旭"
print(user_name)

number1 = 5
number2 = 2.5
print(number1 + number2)

last_name= "侍"
first_name= "太郎"
sister_name= "花子"

print(f"私の名前は{last_name}{first_name}です。私の姉の名前は{sister_name}です。")

user_names = ["侍太郎", "侍一郎", "侍次郎", "侍三郎", "侍四郎"]
print(user_names[1])

user_names[1] = "侍花子"
print(user_names)

user_names.append("侍五郎")
print(user_names)

user_names.pop(2)
print(user_names)

country_names = "日本", "アメリカ", "イギリス", "フランス"

print(country_names[2])
print(country_names)

prime_numbers = {2, 5, 2, 7, 3, 5, 5}
print(prime_numbers)

prime_numbers.add(11)
print(prime_numbers)

prime_numbers.remove(3)
print(prime_numbers)

personal_data = {"name": "侍太郎", "age": 36, "gender": "男性"}

print(personal_data["name"])
print(personal_data)
personal_data["address"] = "東京都"
personal_data.pop("name")

print(personal_data)

import random

num = random.randint(0,4)

print(num)

if 1 < num and num < 3:
  print("変数numは1より大きく、3より小さいです")
else:
  print("and条件が成り立ちませんでした")

if num == 1 or num == 3:
  print("変数numは1または3です")
else:
  print("or条件が成り立ちませんでした")

for i in range(1,11):
  if i % 2 == 0:
    continue
  print(i)

for i in range(1,11):
  if i % 2 ==1:
    continue
  print(i)

#ランダムな整数を利用するため、記述が必要です。
import random

# 変数numに0~4までのランダムな整数を代入する
num = random.randint(0, 4)

# 変数numの値が0以外である間、変数numの値を出力し続ける
while num != 0:
 num = random.randint(0, 4)
 print(num)

import random
num = random.randint(0,4)
print(f"最初の値は{num}です。")

while num != 0:
  num = random.randint(0,4)
  print(f"現在の値は{num}です。")

import random
num = random.randint(0,4)
i = 1

print(f"最初の値は{num}です。")

while num != 0:
  num = random.randint(0, 4)

  if i == 5:
    print("5回目なので繰り返し処理を強制終了します。")
    break

  print(f"現在の値は{num}です")
  i = i + 1

import random
sum = 0

while sum < 20:
  num = random.randint(1,10)
  print(f"{num}が出ました。")

  if num % 2 == 0:
    print("偶数なので加算しません。")
    continue

  sum = sum + num
  print(f"現在の合計は{sum}です。")

user_names = ["侍太郎", "侍一郎", "侍二郎", "侍三郎", "侍四郎"]

for user_name in user_names:
 print(user_name)

user_names = ["侍太郎", "侍一郎", "侍次郎", "侍三郎", "侍四郎"]

for user_name in user_names:
  print(user_name)

personal_data = {"name": "侍太郎", "age": 36, "gender": "男性"}

for key, value in personal_data.items():
  print(f"{key}は{value}です。")

# 連想配列personal_dataの値を1つずつ順番に出力する
for value in personal_data.values():
 print(value)

user_names = ["侍太郎", "侍一郎", "侍次郎", "侍三郎", "侍四郎"]

for index, value in enumerate(user_names):
  print(f"{index}:{value}")

user_names = ["侍太郎", "侍一郎", "侍次郎", "侍三郎", "侍四郎"]
target = "侍次郎"

for user_name in user_names:
  print(user_name)

  if user_name == target:
    print(f"{target}さんが見つかったので、繰り返し処理を強制終了します。")
    break

score = {
    "国語": 80,
    "数学": 55,
    "理科": 70,
    "社会": 85,
    "英語": 60
}
print("合格した科目は以下のとおりです。")

for key, value in score.items():
  if value < 70:
    continue
  print(f"{key}:{value}点")

def say_good_morning():
  print("おはようございます！")
  print("昨日はよく眠れましたか？")
  print("今日も一日頑張りましょう!")

def say_good_evening():
  print("こんばんは!")
  print("今日も一日お疲れ様でした。")

say_good_morning()

say_good_evening()

def add_two_arguments(price, shipping_fee):
  total = price + shipping_fee

  print(f"{total}円")

add_two_arguments(1200, 500)

purchased = True

def is_purchased():
  if purchased:
    return True
  else:
    return False

if is_purchased():
  print("商品は購入済みです")