# Generated by Django 4.2.6 on 2023-12-06 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_category_alter_subject_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crud.category'),
        ),
    ]
